module.exports = {
  preset: 'ts-jest',
  testEnvironment: 'node',
  roots: ['<rootDir>'],
  collectCoverage: true,
  collectCoverageFrom: [
    'apps/**/*.ts',
    'packages/**/*.ts',
    '!**/*.d.ts',
    '!**/types.ts',
    '!**/*.config.ts',
    '!**/__tests__/**',
    '!**/?(*.)+(spec|test).[jt]s?(x)',
    '!**/*.e2e-spec.ts',
    '!**/test/**',
    '!**/dist/**',
    '!**/build/**',
    '!**/.next/**',
    '!**/.next-dev/**',
    '!**/node_modules/**',
    '!apps/**/test-results/**',
    '!apps/**/e2e/**',
    '!apps/api/src/scratch_debug.ts',
    '!apps/api/src/test-bcrypt.ts',
  ],
  coverageDirectory: '<rootDir>/coverage',
  coverageReporters: ['text', 'lcov', 'json-summary'],
  coverageThreshold: {
    global: {
      statements: 90,
      branches: 85,
      functions: 90,
      lines: 90,
    },
  },
  testMatch: ['**/?(*.)+(spec|test).[jt]s?(x)'],
  testPathIgnorePatterns: ['/node_modules/', '/dist/', '/build/', '/.next/', '/.next-dev/', '/e2e/', '/apps/desktop/tests/', '/.claude/', '/.claude/worktrees/', '/tests/', '.*\\.e2e-spec\\.ts$'],
  transform: {
    '^.+\\.(ts|tsx|js|jsx)$': ['ts-jest', {
      tsconfig: {
        rootDir: '.',
        baseUrl: '.',
        emitDecoratorMetadata: false,
        experimentalDecorators: true,
        ignoreDeprecations: '6.0',
        jsx: 'react-jsx',
        resolveJsonModule: true,
        paths: {
          '@smart-erp/database/schema': ['packages/database/src/schema/index.ts'],
          '@smart-erp/database/drizzle': ['packages/database/src/drizzle.ts'],
          '@smart-erp/database': ['packages/database/src/index.ts'],
          '@smart-erp/*': ['packages/*/src/index.ts'],
        },
      },
    }],
  },
  moduleNameMapper: {
    '^@smart-erp/database/schema$': '<rootDir>/packages/database/src/schema/index.ts',
    '^@smart-erp/database/drizzle$': '<rootDir>/packages/database/src/drizzle.ts',
    '^@smart-erp/database$': '<rootDir>/packages/database/src/index.ts',
    '^@smart-erp/(.*)$': '<rootDir>/packages/$1/src/index.ts',
  },
};
