name: Release

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      version:
        description: Release version
        required: true
        default: v0.5.0

jobs:
  publish-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build all apps
        run: pnpm build

      - name: Create Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          if [ -z "$VERSION" ] && [ -n "${{ github.event.inputs.version }}" ]; then
          fi

          gh release create "$VERSION" --title "Release $VERSION"
          --notes "Latest updates" --draft=false
          if [ -z "$VERSION" ] && [ -n "${{ github.event.inputs.version }}" ]; then
          fi

          gh release create "$VERSION" --title "Release $VERSION"
          --notes "Latest updates" --draft=false

